spring.application.name=reservation_system


# DB 연결 정보 (PostgreSQL 기본 포트는 5432입니다)
spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_db
spring.datasource.username=bakery_admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL 방언(Dialect) 설정 (DB 특유의 기능을 쓰기 위함)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect